name: Husky Pre-Pull Request Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions for shell script
        run: chmod +x check.sh

      - name: Run environment variable check script
        run: ./check.sh