name: Husky Pre-Pull Request Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check if API_KEY is set
        run: |
          if [ -z "${{ secrets }}" ]; then
            echo "API_KEY is not set"
            exit 1
          else
            echo "API_KEY is set"
            echo "${{ secrets }}"
          fi