name: Husky Pre-Pull Request Check
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print all environment variables
        run: |
          echo "Environment Variables:"
          printenv

      - name: Print all vars context as JSON
        run: |
          echo "Vars context:"
          echo "${{ toJSON(vars) }}"

          
      - name: Print environment variables 2
        run: printenv

        
