name: Husky Pre-Pull Request Check
on:
  pull_request:
    branches:
      - main
      - develop
# on:
#   workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set environment variables explicitly in the job step
      - name: Print environment variables
        env:
          env_var: ${{ env.ENVIRONMENT }}
          env_var_2: ${{ vars.ENVIRONMENT }}
          env_var_3: ${{ secrets.NAME_X }}
        run: |
          echo "env_var: $env_var"
          echo "env_var_2: $env_var_2"
          echo "env_var_3: $env_var_3"
