name: Husky Pre-Pull Request Check
on:
  pull_request:
    branches:
      - main
      - develop
# on:
#   workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    environment: ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "env_var_1: ${{ vars.ENVIRONMENT }}"
          echo "env_var_2: ${{ secrets.NAME_X }}"
          
      - name: Print environment variables 2
        run: printenv
