name: Husky Pre-Pull Request Check

on:
  pull_request:
    branches:
      - main
      - develop
# on:
#   workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  env_var_2: ${{ vars.ENVIRONMENT }}
  env_var_3: ${{ secrets.NAME_X }}

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_ENV: $ENVIRONMENT"
          echo "variable from shell environment : $env_var"
          echo "variable from shell environment : $env_var_2"
          echo "variable from shell environment : $env_var_3"
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Set permissions for shell script
      #   run: chmod +x check.sh

      # - name: Run environment variable check script
      #   run: ./check.sh